sonar.projectKey=soen-390-the-irs_backend

sonar.organization=soen-390-the-irs

sonar.host.url=https://sonarcloud.io

sonar.sources=app/src/main/java

sonar.tests=app/src/test/java

sonar.java.binaries=app/build/intermediates/javac/debug/classes,app/build/intermediates/built_in_kotlinc/debug/compileDebugKotlin/classes

sonar.kotlin.file.suffixes=.kt,.kts

sonar.coverage.jacoco.xmlReportPaths=app/build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml

sonar.android.lint.report=app/build/reports/lint-results.xml

sonar.verbose=true