sonar.projectKey=soen-390-the-irs_backend
sonar.organization=soen-390-the-irs
sonar.host.url=https://sonarcloud.io

sonar.sources=app/src/main/java
sonar.tests=app/src/test/java
sonar.sourceEncoding=UTF-8

sonar.java.binaries=app/build/intermediates/built_in_kotlinc/debug/compileDebugKotlin/classes

sonar.coverage.jacoco.xmlReportPaths=app/build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml

sonar.kotlin.source.version=2.0

sonar.coverage.exclusions=\
  **/*$*.*,\
  **/*$DefaultImpls*,\
  **/SearchResult$*,\
  **/*$getRoute$*,\
  **/R.java,\
  **/R$*.java,\
  **/BuildConfig.*,\
  **/Manifest*.*,\
  **/*Test*.*,\
  **/android/**/*.*,\
  **/com/example/myapplication/logic/SharedPrefsCalendarPreferences*,\
  **/com/example/myapplication/logic/GoogleCalendarProvider*,\
  **/com/example/myapplication/logic/SimpleMockRouteProvider*,\
  **/com/example/myapplication/data/JsonSchedule*,\
  **/com/example/myapplication/data/JsonStop*,\
  **/com/example/myapplication/data/ShuttleRoute*,\
  **/com/example/myapplication/data/CampusBuildingNameProvider*,\
  **/com/example/myapplication/data/JsonShuttleData*,\
  **/com/example/myapplication/ui/components/**,\
  **/com/example/myapplication/ui/theme/**,\
  **/MapViewModel$navigateToBuildingCode$*,\
  **/MapViewModel$refreshLocation$*,\
  **/com/example/myapplication/ui/viewmodel/MapViewModel*,\
  **/com/example/myapplication/MainActivity*,\
  **/com/example/myapplication/logic/TravelMode*,\
  **/com/example/myapplication/ui/screens/**,\
  **/com/example/myapplication/analytics/**,\
  **/MyCustomApplication.*,\
  **/com/example/myapplication/MapsActivity*,\
  **/com/example/myapplication/MyApplication*,\
  **/com/example/myapplication/telemetry/**,\
  **/com/example/myapplication/map/**,\
  **/com/example/myapplication/shuttle/**,\
  **/*ComposableSingletons*,\
  **/*ComposableInvoker*,\
  **/*Composable$*,\
  **/*ViewActions*,\
  **/*_Factory*,\
  **/*$Lambda$*.*,\
  **/ui/theme/**

sonar.verbose=true