sonar.projectKey=soen-390-the-irs_backend
sonar.organization=soen-390-the-irs

sonar.branch.autoconfig.enabled=true

sonar.sources=app/src/main
sonar.tests=app/src/test,app/src/androidTest

sonar.java.binaries=app/build/intermediates/classes/debug,app/build/intermediates/javac/debug/classes

# Points Sonar at the Kotlin compiled classes
sonar.kotlin.binaries=app/build/tmp/kotlin-classes/debug

sonar.kotlin.file.suffixes=.kt,.kts

sonar.android.lint.report=app/build/reports/lint-results.xml

sonar.coverage.jacoco.xmlReportPaths=**/jacocoTestReport.xml