name: Refactor
description: Suggeest a refactor of existing code.
title: "[REFACTOR]: "
labels: [refactor]
assignees: []
body: 
  - type: markdown
    attributes:
      value: |
        ## Refactor Request
        Please describe the refactor.
  - type: input
    id: area
    attributes: 
      label: Affected Area
      placeholder: e.g., API, UI components
    validations:
      required: true
  - type: textarea
    id: current_problem
    attributes:
      label: Current Problem
      description: What is wrong with the current implementation?
      placeholder: Explain duplication, perfomance issues, etc.
    validations:
      required: true
  - type: textarea
    id: proposed_solution
    attributes:
      label: Proposed Refactor
      description: Describe how the code should be improved
    validations:
      required: true
  - type: checkboxes
    id: impact
    attributes:
      label: Expected Impact
      options:
        - label: Improves performance
        - label: Removes duplication
        - label: Simplifies architechture
  - type: checkboxes
    id: breaking_changes
    attributes:
      label: Breaking Changes?
      options:
        - label: Yes
        - label: No

