package com.example.myapplication.data

import android.content.Context
import com.google.android.gms.maps.model.LatLng
import com.google.gson.Gson
import com.example.myapplication.R
data class JsonLatLng(val latitude: Double, val longitude: Double)

data class Building(
    val name: String,
    val code: String,
    val wayID: Long,
    val outline: List<JsonLatLng>?, // Make nullable for safety
    val isCampusBuilding: Boolean = true
) {
    fun getGoogleOutline(): List<LatLng> = outline?.map { LatLng(it.latitude, it.longitude) } ?: emptyList()
}

data class Campus(
    val name: String,
    val center: JsonLatLng,
    val buildings: List<Building>,
    val outline: List<JsonLatLng>?, // Make nullable for safety
    val defaultZoom: Float = 17f
) {
    fun getGoogleCenter(): LatLng = LatLng(center.latitude, center.longitude)
    fun getGoogleOutline(): List<LatLng> = outline?.map { LatLng(it.latitude, it.longitude) } ?: emptyList()
}

data class CampusDataWrapper(val campuses: List<Campus>)

object CampusRepo {
    private var allCampuses: List<Campus> = emptyList()

    fun initialize(context: Context) {
        android.util.Log.d("DATA_CHECK", "1. Initialize started (using res/raw)")
        try {
            // Use the Resource ID generated by Android for the file in res/raw/campuses.json
            val inputStream = context.resources.openRawResource(R.raw.campuses)

            val jsonString = inputStream.bufferedReader().use { it.readText() }
            android.util.Log.d("DATA_CHECK", "2. JSON read success. Length: ${jsonString.length}")

            val wrapper = Gson().fromJson(jsonString, CampusDataWrapper::class.java)

            if (wrapper != null) {
                allCampuses = wrapper.campuses
                android.util.Log.d("DATA_CHECK", "3. Success! Loaded ${allCampuses.size} campuses")
            } else {
                android.util.Log.e("DATA_CHECK", "3. ERROR: Gson returned null wrapper")
            }
        } catch (e: Exception) {
            android.util.Log.e("DATA_CHECK", "FATAL ERROR: ${e.message}")
            e.printStackTrace()
        }
    }

    // This now accepts Google's LatLng so MapsActivity is happy
    fun getCampus(point: LatLng): Campus? {
        val inside = allCampuses.find { isInsidePolygon(point, it.getGoogleOutline()) }
        if (inside != null) return inside

        return allCampuses.minByOrNull { campus ->
            val center = campus.getGoogleCenter()
            Math.sqrt(Math.pow(point.latitude - center.latitude, 2.0) +
                    Math.pow(point.longitude - center.longitude, 2.0))
        }
    }

    fun getCampusByName(name: String): Campus? = allCampuses.find {
        it.name.trim().equals(name.trim(), ignoreCase = true)
    }
    private fun isInsidePolygon(point: LatLng, polygon: List<LatLng>): Boolean {
        if (polygon.isEmpty()) return false
        var intersectCount = 0
        for (j in polygon.indices) {
            val i = if (j == 0) polygon.size - 1 else j - 1
            if (rayCastIntersect(point, polygon[i], polygon[j])) intersectCount++
        }
        return intersectCount % 2 != 0
    }

    fun setTestCampuses(campuses: List<Campus>) {
        allCampuses = campuses
    }
    private fun rayCastIntersect(tap: LatLng, vertA: LatLng, vertB: LatLng): Boolean {
        val aY = vertA.latitude; val bY = vertB.latitude
        val aX = vertA.longitude; val bX = vertB.longitude
        val pY = tap.latitude; val pX = tap.longitude

        // Prevent horizontal lines from causing issues or division by zero
        if (aY == bY) return false

        if ((aY > pY && bY > pY) || (aY < pY && bY < pY) || (aX < pX && bX < pX)) return false

        val m = (aY - bY) / (aX - bX)
        val bee = aY - m * aX
        val xIntersection = (pY - bee) / m
        return xIntersection > pX
    }
}